### PR TITLE
Improved Dutch locale

### PR DESCRIPTION
**Pull request by TheRealDadbeard**
Translated everything but commands.

### CODE REVIEW

**Comment by TheRealDadbeard** [comment]
I'm translating even more script to correct german, done a bunch already if completed everything will pull request them across all scripts.

**Comment by ElPumpo** [comment]
.. All locales start lower case, there's some exceptions

**Comment by TheRealDadbeard** [comment]
But why though? This looks horrible and sentences start with an upper case...

**Comment by majormarcin** [comment]
@TheRealDadbeard 
the script itself begins with uppercase letters in the right places, so you do not have to be scared
if you start a sentence in a language file with a capital letter, then the entire string will be in uppercase letters
this is the reason why the words and sentences in the language file should be in lower case
if it starts with ~ then the next letter can be large

**Comment by ElPumpo** [comment]
> if you start a sentence in a language file with a capital letter, then the entire string will be in uppercase letters 

this is not true, only the first letter becomes uppercase, if you don't want it to be uppercase, eg if you want to spell `iPhone` then do something like this `~s~iPhone`
Thanks for explaining @majormarcin tho. As I said wont merge til changes have been done.

**Pull request closed without merging**
