### PR TITLE
Add MK2 Weapons

### PR DESCRIPTION
**Pull request by tracid56**
Add MK2 Weapons & Local FR

### CODE REVIEW

**Comment by ElPumpo** [comment]
Missing weapon components, extended ammo information and locales for all languages. Also weapons the the config are sorted by weapon type (melee, pistols, smgs, lmgs, assault rifles, etc)

**Comment by Profex1999** [comment]
MK2 weapons have different components instead of normal ones.  The tints also are different, MK2 weapons have like 30 or so tints and their number is different from the normal ones. Look at this link to understand better what I mean https://wiki.rage.mp/index.php?title=Weapons_Tints

**Comment by XvenDeR** [comment]
And look this link to find components hash keys
https://wiki.rage.mp/index.php?title=Weapons_Components
Have fun adding them. 💃

**Comment by indilo53** [comment]
We have complete weapon dump and using gxt for translations now :)

**Pull request closed without merging**
