### PR TITLE
added user "needs" to remove esx_status and esx_basicneeds

### PR DESCRIPTION
**Pull request by xDope7137**
This is just the starting of creating needs for users inside the es_extended and stopping servers to use esx_status and esx_basicneeds.

I can further convert the whole scripts with exports if es_extended developers allow me to.

Resmon will be around 0.04 MS (client-side data update) and will update needs the same as es_extended updates cash and bank.

I will make a script or basically integrate it into es_extended where we can have exports to add and remove 'thirst, food, stress, drunk level, etc.'

Any future ideas depend on ESX's reply.

Thanks.

### CODE REVIEW

**Comment by Fantastic-Dave** [comment]
remember to add in a change to the sql file too :)

**Comment by xDope7137** [comment]
Still waiting for someone to allow it to be added in es_extended so I can basically add more functions.

**Comment by indilo53** [comment]
Hello :) I added you on discord, I am intersted to find an alternative to what we have

**Comment by GlobbinTerpenes** [comment]
this seems real cool

**Comment by indilo53** [comment]
We need new stuff for this but cannot merge as-is

**Pull request closed without merging**
