### PR TITLE
Steam Name

### PR DESCRIPTION
**Pull request by xDope7137**
Added steam name in DB to allow server owners to find certain players without finding them by their steam hex.

### CODE REVIEW

**Comment by xDope7137** [comment]
I forgot that ESX still uses the RC Licence. I think mostly all wants to go back to steam hex instead of RC licence.

**Comment by ArkSeyonet** [comment]
The reason it went to R* license was because of the chance that Steam will remove the ability for us to get SteamID, but unsure what will happen with that now.

**Comment by deviljin112** [comment]
Continuing from Ark's point, Epic players wont have SteamID... Also if you ban a player on their R* license they are banned and unable to come back, with SteamID you can just log in to a new account, share GTA5 with new acc and play on the server you were just banned on because of new SteamID... R* license is much more static, consistent, and issue-free (at least at the moment)

**Comment by XvenDeR** [comment]
No one bans people on just 1 identifier. 
IP, steam, RC license is mandatory.

And i thought steam name was removed, because of some symbols breaking the database.

**Comment by RockySouthpaw** [comment]
You can purchase GTA from the rockstar store and sign into a steam account. I’m assuming the same logic applies to if you purchased from epic games. As long as the user has steam open then you can grab the steam identifier. (This is how it’s always been for me as I don’t even own GTA on steam.)

While yes, banning via license is much easier. However, steam identifiers are still useful in their own way just not the best choice for moderation. You can also grab their identifier easier just by getting their steam profile url. As far as I’m aware, there is no such tools for RC License. (I may be wrong though.)

**Comment by ArkSeyonet** [comment]
> No one bans people on just 1 identifier.
> IP, steam, RC license is mandatory.
> Epic games can freely play with while getting steam identifier, they will simply need both. Epic games and Steam launched.
> And i thought steam name was removed, because of some symbols breaking the database.

Yeah, people with strange symbols in their steam names could break stuff on the db. That's why it was removed, if I also remember correctly.

**Pull request closed without merging**
