### PR TITLE
Debug SQL and loading screen errors

### PR DESCRIPTION
**Pull request by SezonDev**
Pending an update.

Loading screen debug and sql errors

### CODE REVIEW

**Comment by deviljin112** [comment]
master is 2.0 and does not need .sql file, it generates them on demand within lua itself...

If you meant to push it to 1.final please make a PR to the correct branch...

**Comment by SezonDev** [comment]
In fact there is an error it generates the other tables well but not:

accounts
datastores
inventories

**Comment by deviljin112** [comment]
Have a look at develop branch, and how the db queries are handled.

We have removed .sql files for a reason as they are being generated within .lua and pushed with MySQL query. Adding these tables back to .sql defeats the point that we are trying to achieve.

Use develop if you having some issues with master as its got more features and is a little bit more polished.

**Comment by SezonDev** [comment]
No worries thank you i watch this

**Pull request closed without merging**
