### PR TITLE
Added events on money transactions

### PR DESCRIPTION
**Pull request by xcxooxl**
Added events when user creates money transactions,
Could be used to make economy plugins/anticheats maybe, etc

### CODE REVIEW

**Comment by BackrndSource** [comment]
After in other script you can call
```
RegisterServerEvent('esx:onSetMoney',
AddEventHandler('esx:onSetMoney', function(transactionData){
[...]
}
`````
?
I think this is good idea!

**Comment by xcxooxl** [comment]
Yes, that's the idea.

**Comment by XvenDeR** [comment]
After this all purchases in server was broken and bank operations.

**Comment by ElPumpo** [comment]
No thanks, we're not going to merge this pr

**Pull request closed without merging**
