### PR TITLE
Fixed vehicle network id issues by removing mission entity re

### PR DESCRIPTION
**Pull request by dexslab**
gistration adding proper manifest version and setting up vehicle migration from config

### CODE REVIEW

**Comment by indilo53** [comment]
Intersting, what it does exactly ?

**Comment by dexslab** [comment]
This allows proper migration of network ids to other scripts like ELS Plus, when you spawn a vehicle from the police garage we cannot get a proper network id from your script with this it allows us to properly register and control the vehicle with ELS Plus

**Comment by indilo53** [comment]
Okay thanks 👍

**Comment by benzon** [comment]
I think this update is a mistake, the altering of the manifest brok way more then it fixed, it might allow els-plus but breaks a lot of esx modules like policejob object-spawner.

els-fivem worked greate with the old system.

**Pull request merged**
