### PR TITLE
Updated Portuguese translation

### PR DESCRIPTION
**Pull request by Santagain**

### CODE REVIEW

**Comment by ElPumpo** [comment]
Upper case? No

**Comment by ElPumpo** [comment]
Are you going to fix it or not?

**Comment by Santagain** [comment]
in the portuguese language of brazil the uppercase rules are different, but i will standardize everything for minuscule as you wish

**Comment by ElPumpo** [comment]
No you dont understand, it's automaticly turned into upper case if needed by the code.

**Pull request merged**
