### PR TITLE
Workaround for #118

### PR DESCRIPTION
**Pull request by SaltyGrandpa**
This should be a pretty elegant workaround for #118. Checks if the provided `killerId` is an active network player, if they are the script behaves as it previously did. If `killerId` is not an active network player, it defaults the values to 0. 

I was unable to reproduce the error with this implemented and saw no adverse effects. The only potential side effect to this fix is that if a user had a resource displaying information when the player is killed, it may be inaccurate (showing 0 distance if/when an NPC kills a player, etc.).

Let me know if any changes need made.

### CODE REVIEW

**Comment by ElPumpo** [comment]
5 commits..?

**Comment by SaltyGrandpa** [comment]
That's just the changes that I made to my fork. I don't know why it didn't start at 33d1abc, which was me bringing my fork up to date with the master branch. There's only one file changed.

**Comment by ElPumpo** [comment]
Right. Either this workaround adds way too many unnecessary but is a step in the right direction.

**Comment by SaltyGrandpa** [comment]
I mean, it adds like 4 logical operators. It's not a heavy change. It was the lightest change that I could work out while still keeping the same data in the table to not break other resources that rely on that data. Open to suggestions, or feel free to close out. ¯\_(ツ)_/¯

**Comment by SaltyGrandpa** [comment]
For what it's worth, I've had this fix running on my server since I submitted the PR. I have yet to be able to replicate the old issue and have seen no side effects. Not sure how you'd like my to reduce the logic down further without losing support for scripts that rely on this data. Let me know thoughts, open to constructive criticism.

**Comment by ElPumpo** [comment]
Pushed 7e31fc90f4e589323a5a8d5d7035023186094774 today (bottom of the commit diff). Let's hope the `NetworkIsPlayerActive()` check is enough

**Comment by SaltyGrandpa** [comment]
I haven't been able to replicate the issue since these changes, hopefully it works for all use cases.

**Comment by SaltyGrandpa** [comment]
@ElPumpo did an official fix for this ever get committed?

**Comment by ElPumpo** [comment]
Yes as the code was re written

**Pull request closed without merging**
