### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shortybsd**
Missing async dependency.

### CODE REVIEW

**Comment by z4q** [comment]
please close this one. duplicate #836

**Comment by shortybsd** [comment]
One is for develop branch, other is for master. Master needs to be updated asap to get rid of people slamming the same question over and over again.

**Comment by z4q** [comment]
oh. just do on develop branch only. later ask dev to merge to master. but in my config in don't put "ensure async" also can run with no problem.

**Comment by shortybsd** [comment]
Will do, you lost me on the 2nd sentence. Both master and develop in fxmanifest.lua require async. So ensure async needs to be on both.

**Pull request closed without merging**
